# Generated by Django 5.2.13 on 2026-04-27 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Seed Shop', 'Seed Shop'), ('Fertilizer Store', 'Fertilizer Store'), ('Pesticide Supplier', 'Pesticide Supplier')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, help_text='Applicable region', max_length=100, null=True)),
                ('crop', models.CharField(blank=True, help_text='Applicable crop', max_length=100, null=True)),
                ('benefits', models.TextField()),
                ('eligibility', models.TextField()),
                ('how_to_apply', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CropReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100)),
                ('user_condition_input', models.TextField()),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Moderate', 'Moderate'), ('Poor', 'Poor')], max_length=20)),
                ('issues_identified', models.TextField()),
                ('recommendations', models.TextField()),
                ('step_by_step_guidance', models.TextField()),
                ('loss_prediction', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('crops', models.CharField(blank=True, help_text='Comma-separated list of crops', max_length=512, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
